lfname: Echo Message on Multiple CentOS 9 Runners

on:
  workflow_dispatch:

jobs:
  echo-on-prflow:
    name: Echo on CentOS 9 PR Flow Runner
    runs-on: [ self-hosted, linux, x64 ]

    steps:
      - name: Say Hello from PR Flow Runner
        run: |
          echo "👋 Hello from CentOS 9 - PR Flow Runner"
          hostname
          date

  echo-on-node2:
    name: Echo on CentOS 9 Node 2
    runs-on: [ node2 ]
    needs: echo-on-prflow

    steps:
      - name: Say Hello from Node 2
        run: |
          echo "🚀 Hello from CentOS 9 - Node 2"
          hostname
          date
