name: SSH Copy SSH Key via GitHub

on:
  workflow_dispatch:

jobs:
  get-key:
    runs-on: [self-hosted, prflow]
    outputs:
      pubkey: ${{ steps.extract-key.outputs.key }}

    steps:
      - name: Extract public key
        id: extract-key
        run: |
          KEY=$(sudo cat /home/devops/.ssh/id_rsa.pub)
          echo "key=${KEY}" >> $GITHUB_OUTPUT

  deploy-key:
    needs: get-key
    runs-on: [self-hosted, node2]
    
    steps:
      - name: Add key to authorized_keys
        run: |
          sudo mkdir -p /home/devops/.ssh
          echo '${{ needs.get-key.outputs.pubkey }}' | sudo tee -a /home/devops/.ssh/authorized_keys
          sudo chown -R devops:devops /home/devops/.ssh
          sudo chmod 700 /home/devops/.ssh
          sudo chmod 600 /home/devops/.ssh/authorized_keys
