name: devops-sshGenerate SSH Key for DevOps User on prflow

on:
  workflow_dispatch:

jobs:
  generate-ssh-key:
    runs-on: [self-hosted, prflow]

    steps:
      - name: Check if devops user exists
        id: check-user
        run: |
          if id -u devops >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "User 'devops' does not exist - create it first"
            exit 1
          fi

      - name: Create .ssh directory
        run: |
          sudo -u devops mkdir -p /home/devops/.ssh
          sudo chmod 700 /home/devops/.ssh

      - name: Generate SSH key pair
        run: |
          sudo -u devops ssh-keygen -t rsa -b 4096 -f /home/devops/.ssh/id_rsa -N "" -q
          echo "SSH key generated for devops user"

      - name: Set proper permissions
        run: |
          sudo chown -R devops:devops /home/devops/.ssh
          sudo chmod 600 /home/devops/.ssh/id_rsa
          sudo chmod 644 /home/devops/.ssh/id_rsa.pub

      - name: Verify key generation
        run: |
          echo "Verification:"
          echo "Private key exists: $(sudo test -f /home/devops/.ssh/id_rsa && echo 'Yes' || echo 'No')"
          echo "Public key exists: $(sudo test -f /home/devops/.ssh/id_rsa.pub && echo 'Yes' || echo 'No')"
          echo "Public key content:"
          sudo cat /home/devops/.ssh/id_rsa.pub
