

name: inventory

on:
  workflow_dispatch:

jobs:
  heredoc-demo:
    runs-on: prflow

    steps:
      - name: Create file with EOF
        run: |
          su - devops 
          sudo cat << EOF > /home/devops/inventory
          [web]
          node2

          [database]
          node3
          
          EOF
          sudo cat /home/devops/inventory
