name: Update /etc/hosts on Runners

on:
  workflow_dispatch:

jobs:
  update-hosts:
    strategy:
      matrix:
        runner: ["prflow", "node2"]
    runs-on: [ "self-hosted", "${{ matrix.runner }}"]

    steps:
      - name: Get current IP address
        id: get-ip
        run: |
          IP=$(hostname -I | awk '{print $1}')
          echo "IP address: $IP"
          echo "ip=$IP" >> $GITHUB_OUTPUT

      - name: Update /etc/hosts
        run: |
          echo "Updating /etc/hosts with:"
          echo "${{ steps.get-ip.outputs.ip }} ${{ matrix.runner }}" | sudo tee -a /etc/hosts
          echo "Current /etc/hosts:"
          cat /etc/hosts

      - name: Verify connectivity
        run: |
          ping -c 2 prflow || echo "Could not ping prflow"
          ping -c 2 node2 || echo "Could not ping node2"
