name: Update /etc/hosts with Runner IPs

on:
  workflow_dispatch:

jobs:
  update-hosts:
    strategy:
      matrix:
        runner: ["prflow", "node2" ]
    runs-on: [self-hosted, ${{ matrix.runner }}]

    steps:
      - name: Get current IP address
        id: get-ip
        run: |
          IP=$(hostname -I | awk '{print $1}')
          echo "IP address: $IP"
          echo "ip=$IP" >> $GITHUB_OUTPUT

      - name: Update /etc/hosts
        run: |
          echo "Adding entries to /etc/hosts"
          echo "${{ steps.get-ip.outputs.ip }} ${{ matrix.runner }}" | sudo tee -a /etc/hosts
          echo "Updated /etc/hosts:"
          cat /etc/hosts

      - name: Verify changes
        run: |
          ping -c 2 prflow || true
          ping -c 2 node2 || true
          ping -c 2 node3 || true
