name: Update /etc/hosts (Hardcoded IPs)

on:
  workflow_dispatch:

jobs:
  update-hosts:
    strategy:
      matrix:
        runner: ["prflow", "node2"]
    runs-on: ["self-hosted", "${{ matrix.runner }}"]

    steps:
      - name: Update /etc/hosts
        run: |
          echo "10.128.0.7 prflow" | sudo tee -a /etc/hosts
          echo "10.128.0.8 node2" | sudo tee -a /etc/hosts
          echo "Updated /etc/hosts:"
          cat /etc/hosts
