name: Run Ansible Playbook

on:
  workflow_dispatch:

jobs:
  run-ansible:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v4

      - name: Execute Ansible Playbook
        env:
          DEVOPS_PASS: ${{ secrets.DEVOPS_PASSWORD }}
        run: |
          echo "$DEVOPS_PASS" | sudo -S -u devops \
            cd /home/devops/ansible \
            ansible-playbook all -i /home/devops/ansible/inventory/inventory.yaml \
           ansible/playbook1-webserver.yaml
