name: Run Ansible Playbook

on:
  workflow_dispatch:

jobs:
  run-ansible:
    runs-on: devops
    
    steps:
      - uses: actions/checkout@v4

      - name: Execute Ansible Playbook
        env:
          DEVOPS_PASS: ${{ secrets.DEVOPS_PASSWORD }}
        run: |
         
           ansible-playbook all -i /home/devops/ansible/inventory/inventory.yaml \
           ansible/playbook1-webserver.yaml
