name: Run Ansible Playbook
on:
 push:
   branches: [main]
 pull_request:
   branches: [main]
 workflow_dispatch:
  

jobs:
  ansible-playbook:
    runs-on: [devops ]  # Change this if you're not using a self-hosted runner

    
    steps:
      - uses: actions/checkout@v4

      - name: Execute Ansible Playbook
     
        run: |  
           ansible-playbook  /home/devops/ansible/actions-runner/_work/p1/p1/ansible/playbook1-webserver.yaml -i /home/devops/ansible/inventory/inventory.yaml
