
name: Run Ansible Playbook

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  

jobs:
  ansible-playbook:
    runs-on: [prflow]  # Change this if you're not using a self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure Ansible is installed
        run: |
          if ! command -v ansible >/dev/null 2>&1; then
            echo "Installing Ansible..."
            sudo dnf install -y epel-release
            sudo dnf install -y ansible
          else
            echo "Ansible already installed."
          fi

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbook1-webserver.yaml -i /home/devops/inventory/inventory.yaml
