name: Run Ansible Commands

on:
  workflow_dispatch:

jobs:
  run-ansible:
    runs-on: [prflow]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install expect
      run: sudo apt-get install -y expect

    - name: Run Ansible commands
      run: |
        /usr/bin/expect <<EOD
        set timeout 30
        
        # First spawn: Change directory and run Ansible commands
        spawn sudo -u devops bash -c "
          cd /home/devops/ansible/ && \
          ansible all --list-hosts -i inventory/inventory.yaml && \
          ansible all -m package -a 'name=git state=present' -i inventory/inventory.yaml && \
          ansible all -m user -a 'name=shruti state=present' -i inventory/inventory.yaml && \
          ansible all -a 'id shruti' -i inventory/inventory.yaml
        "
        
        expect {
          "password for" {
            send "${{ secrets.DEVOPS_PASSWORD }}\r"
            
          }
         
          eof
        }
        EOD
      shell: bash
