name: Run Ansible as devops user

on:
  workflow_dispatch:

jobs:
  run-ansible:
    runs-on: [prflow]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install expect (if needed)
      run: sudo dnf install -y expect

    - name: Run Ansible command as devops user
      run: |
        # Using expect to handle password prompt securely
        /usr/bin/expect <<EOD
        spawn cd ansible 
        spawn sudo -u devops ansible all --list-hosts -i /home/devops/ansible/inventory/inventory.yaml
        spawn sudo -u devops ansible all -m yum -a "name=git state=present"
        spawn sudo -u devops ansible all -m user -a "name=shruti state=present"
        spawn sudo -u devops ansible all -m "id shruti" 
        
      shell: bash

    - name: Gather facts (more comprehensive test)
      run: |
        ansible all -m yum -a "name=git state=present"
        ansible all -m user -a "name=shruti state=present"
          ansible all -m "id shruti" 
        
