name: Switch to devops user with password

on:
  workflow_dispatch:  # Manual trigger

jobs:
  switch-user:
    runs-on: [prflow]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Switch to devops user with password
      run: |

        
        # Alternative method using echo (less secure)
        # echo "$DEVOPS_PASSWORD" | sudo -S -u devops bash -c 'whoami'
      shell: bash
      env:
        DEVOPS_PASSWORD: ${{ secrets.DEVOP_PASSWORD }}

    - name: Test connections with ping module
      run: |
        ansible all --list-hosts -i /home/devops/ansible/inventory/inventory.yaml

    - name: Gather facts (more comprehensive test)
      run: |
        ansible all -m yum -a "name=git state=present"
        ansible all -m user -a "name=shruti state=present"
          ansible all -m "id shruti" 
        
